server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
#            - After=2021-12-21T10:33:19.958+08:00[Asia/Shanghai] # 在这个时间之后生效
#            - Before=2021-12-21T10:33:19.958+08:00[Asia/Shanghai] # 在这个时间之前生效
#            - Between=2021-12-21T10:33:19.958+08:00[Asia/Shanghai], 2022-12-21T10:33:19.958+08:00[Asia/Shanghai] # 在这两个时间点之间生效
#            - Cookie=username,zhumengren # 访问需要携带Cookie，并且Cookie的值为zhumengren才能访问
#            - Header=X-Request-Id, \d+   #请求头中要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.mengren.com
#            - Method = GET
#            - Query=username, \d+ # 要有参数名username，并且它的值还是正整数才行

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/discovery   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka