server:
  port: 80
spring:
  application:
    name: openFeign-consumer-order
eureka:
  client:
    register-with-eureka: false # 不注册进eureka服务中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/